# Generated by Django 3.2.16 on 2022-10-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='data',
            new_name='date',
        ),
    ]
