# Generated by Django 3.2.16 on 2022-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_data_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='text',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
